#!/bin/bash

#Script to execute the tcl script and the python code for every TCP Variant and CBR rate
echo "Reno/Reno"
echo "CBR		Throughput1		Throughput2		Latency1		Latency2		DropRate1		DropRate2"
a=(1 2 3 4 5 5.5 6 6.5 7 7.5 8 8.5 9 9.3 9.5 9.6 9.8 10)


for i in "${a[@]}"
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns experiment2.tcl Reno Reno "$i"
printf '%s' "$i"
./analyzeData
done

echo "------------------------------------------------------------------------"
echo "NewReno/Reno"
echo "CBR		    Throughput1		    Throughput2		    Latency1		    Latency2		    DropRate1		    DropRate2"
for i in "${a[@]}"
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns experiment2.tcl Newreno Reno "$i"
printf '%s' "$i"
./analyzeData
done

echo "------------------------------------------------------------------------"
echo "Vegas/Vegas"
echo "CBR		    Throughput1		    Throughput2		    Latency1		    Latency2		    DropRate1		    DropRate2"
for i in "${a[@]}"
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns experiment2.tcl Vegas Vegas "$i"
printf '%s' "$i"
./analyzeData
done

echo "------------------------------------------------------------------------"
echo "NewReno/Vegas"
echo "CBR	 Throughput1	 Throughput2	 Latency1	 Latency2	 DropRate1	 DropRate2"
for i in "${a[@]}"
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns experiment2.tcl Newreno Vegas "$i"
printf '%s' "$i"
./analyzeData
done

