#!/bin/bash

#Script to execute the tcl script and the python code for every TCP Variant and CBR rate
echo "Tahoe"
echo "CBR      Throughput               Latency         Packet Drop Rate"
a=(1 2 3 4 5 5.5 6 6.5 7 7.5 8 8.5 9 9.3 9.5 9.6 9.8 10)


for i in "${a[@]}"
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns experiment1.tcl Tahoe "$i"
printf '%s' "$i"
./analyzeData
done

echo "------------------------------------------------------------------------"
echo "Reno"
echo "CBR      Throughput               Latency         Packet Drop Rate"
for i in "${a[@]}"
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns experiment1.tcl Reno "$i"
printf '%s' "$i"
./analyzeData
done

echo "------------------------------------------------------------------------"
echo "NewReno"
echo "CBR      Throughput               Latency         Packet Drop Rate"
for i in "${a[@]}"
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns experiment1.tcl Newreno "$i"
printf '%s' "$i"
./analyzeData
done

echo "------------------------------------------------------------------------"
echo "Vegas"
echo "CBR      Throughput               Latency         Packet Drop Rate"
for i in "${a[@]}"
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns experiment1.tcl Vegas "$i"
printf '%s' "$i"
./analyzeData
done

